// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3R3FuCMvBIKY8mFA8S_hJXSbfrc-FEgI',
    appId: '1:323336171190:web:2103019509b244df61c017',
    messagingSenderId: '323336171190',
    projectId: 'demo1-282df',
    authDomain: 'demo1-282df.firebaseapp.com',
    storageBucket: 'demo1-282df.firebasestorage.app',
    measurementId: 'G-NE14LCQRS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBameue9KKh7BO7TkOK_jsksUKEH-lff_U',
    appId: '1:323336171190:android:09f68319c3d71e2f61c017',
    messagingSenderId: '323336171190',
    projectId: 'demo1-282df',
    storageBucket: 'demo1-282df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI1hEYYstWH4OjBuQ8btlyxggEaMCQy90',
    appId: '1:323336171190:ios:49de68d349c639c461c017',
    messagingSenderId: '323336171190',
    projectId: 'demo1-282df',
    storageBucket: 'demo1-282df.firebasestorage.app',
    iosBundleId: 'com.example.ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI1hEYYstWH4OjBuQ8btlyxggEaMCQy90',
    appId: '1:323336171190:ios:49de68d349c639c461c017',
    messagingSenderId: '323336171190',
    projectId: 'demo1-282df',
    storageBucket: 'demo1-282df.firebasestorage.app',
    iosBundleId: 'com.example.ios',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3R3FuCMvBIKY8mFA8S_hJXSbfrc-FEgI',
    appId: '1:323336171190:web:14899ef41819022161c017',
    messagingSenderId: '323336171190',
    projectId: 'demo1-282df',
    authDomain: 'demo1-282df.firebaseapp.com',
    storageBucket: 'demo1-282df.firebasestorage.app',
    measurementId: 'G-DZ12D4XB5W',
  );
}
